// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tadywvzjmhtiatahgvnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZHl3dnpqbWh0aWF0YWhndm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTM1ODAsImV4cCI6MjA2NTAyOTU4MH0.QT9fLswlcIvusKKMeoMbwEHPrnJipiVi3NcOHZzRJuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);